### PR TITLE
Change run folders back to distinct values

### PR DESCRIPTION
**Pull request by Nightenom**

### CODE REVIEW

**Comment by OrionDevelopment** [comment]
This was done on purpose.

**Comment by OrionDevelopment** [comment]
The aim of this change is to properly support things like the game test framework while it is running in ci. From that perspective it was chosen to unify the run directories so that the structure is easier.

**Comment by Nightenom** [comment]
Yeah, but if you want to run server and client at once you get file clutches. Gonna try local overrides

**Comment by OrionDevelopment** [comment]
The overrides exists exactly for those reason

**Pull request closed without merging**
